---
theme: jekyll-theme-minimal
title: Global Land Mitigation Potential
description: Long-term Scenarios,<br>Interactive Plots &<br>Supplementary Material<br><br>from:<br>Freistetter et al.<br>(2024, manuscript in<br>preparation)<br><br><br><br><br><br><br><br>
---
