title: Global Climate Change Mitigation Potential of Land
description: Freistetter N.C., Ekholm T., Partanen A.I. (2024, manuscript in preparation)
theme: minima
header_pages:
  - Study.md
  - Figures.md
  
