---
theme: jekyll-theme-minimal
title: Global Land Mitigation Potential
description: Long-term Scenarios<br>Interactive Plots &<br>Supplementary Material<br>for Freistetter et al. (manuscript in preparation)
---
