title: Global Land Mitigation Potential
description: test
theme: jekyll-theme-dinky
header_pages:
  - index.md
  - IA_Fig_3.html
  - IA_Fig_2a.html
nav:
  - name: Home
    link: /
  - name: Plotly Plot
    link: /IA_Fig_3.html
  - name: Figure 2a whoop
    link: /IA_Fig_2a.html
