---
theme: jekyll-theme-minimal
title: Global Land Mitigation Potential
description: Long-term Scenarios<br>Interactive Plots &<br>Supplementary Material<br><br>Freistetter et al. (2024, manuscript in preparation)<br><br><br><br><br><br><br><br>
---
